#!/usr/bin/env python3
"""生成 ISA 指令表文档 (单一事实来源: ucpu/isa.py)。

每次增删指令后运行:
    python script/gen_isa_docs.py          # 重写 docs/ISA.md
    python script/gen_isa_docs.py --check  # 校验与当前文档一致 (CI 使用)

分组 (数值区间) 与 ucpu/isa.py Opcode 定义严格一致:
    Base 0-27 | ARM64 28-67 | FP 68-77 | Vector 78-83 | RISC-V 84-110 | SYS 111
"""

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from ucpu.isa import Opcode  # noqa: E402

DOC_PATH = os.path.join(ROOT, 'docs', 'ISA.md')

# (标题, 起始值含, 结束值不含, 说明)
GROUPS = [
    ('Base ISA', 0, 28, '基础指令集: 数据传输/算术/逻辑/控制/栈/IO'),
    ('ARM64 扩展', 28, 68, 'ARM64 风格: 条件/移位/加载存储/分支/位操作 (WFE/WFI/SEV 无事件模型, 语义等同 NOP)'),
    ('FP 浮点扩展', 68, 78, 'IEEE-754 单精度浮点运算与转换'),
    ('Vector 向量扩展', 78, 84, '4-lane 向量算术与加载存储'),
    ('RISC-V 扩展', 84, 111, 'RV64I 风格: 加载存储/立即数/分支/跳转'),
    ('SYS 宿主调用', 111, 112, '宿主系统调用 (CIN 内建函数/浮点支撑)'),
]


def group_members(start: int, stop: int):
    """返回该区间内 Opcode 成员 (按值升序)。"""
    return [m for m in Opcode if start <= m.value < stop]


def build_doc() -> str:
    lines = []
    lines.append('# UCPU 指令集参考 (自动生成)\n')
    lines.append('> 本文档由 `python script/gen_isa_docs.py` 从 `ucpu/isa.py` 自动生成, '
                 '请勿手工编辑。\n')
    lines.append('## 总览\n')
    total = len(Opcode)
    lines.append(f'- 指令总数: **{total}** (Opcode 0..{total - 1})')
    short = {'Base ISA': 'Base', 'ARM64 扩展': 'ARM64', 'FP 浮点扩展': 'FP',
             'Vector 向量扩展': 'Vector', 'RISC-V 扩展': 'RISC-V',
             'SYS 宿主调用': 'SYS'}
    count_line = ' | '.join(f'{short[name]}: {len(group_members(a, b))}'
                            for name, a, b, _ in GROUPS)
    lines.append(f'- 分组: {count_line}\n')
    lines.append('| 分组 | 数量 | 范围 | 说明 |')
    lines.append('|------|------|------|------|')
    for name, a, b, note in GROUPS:
        lo = next(m.value for m in Opcode if m.value == a)
        hi = next(m.value for m in Opcode if m.value == b - 1)
        lines.append(f'| {name} | {len(group_members(a, b))} | {lo}..{hi} | {note} |')
    lines.append('')
    for name, a, b, note in GROUPS:
        members = group_members(a, b)
        lines.append(f'## {name} ({len(members)} 条)\n')
        lines.append('| 助记符 | 编码 | 助记符 | 编码 | 助记符 | 编码 |')
        lines.append('|--------|------|--------|------|--------|------|')
        rows = [members[i:i + 3] for i in range(0, len(members), 3)]
        for row in rows:
            cells = []
            for m in row:
                cells.extend([f'`{m.name}`', str(m.value)])
            while len(cells) < 6:
                cells.append('')
            lines.append('| ' + ' | '.join(cells) + ' |')
        lines.append('')
    lines.append('---')
    lines.append('*Generated by `script/gen_isa_docs.py` from `ucpu/isa.py`.*\n')
    return '\n'.join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description='生成/校验 docs/ISA.md')
    ap.add_argument('--check', action='store_true',
                    help='仅校验现有文档与生成结果一致')
    args = ap.parse_args()

    content = build_doc()
    if args.check:
        if os.path.exists(DOC_PATH):
            with open(DOC_PATH, 'r', encoding='utf-8') as f:
                existing = f.read()
            if existing == content:
                print('ISA doc up to date.')
                return 0
            print('ISA doc OUT OF DATE: run `python script/gen_isa_docs.py`')
            return 1
        print('ISA doc missing: run `python script/gen_isa_docs.py`')
        return 1

    os.makedirs(os.path.dirname(DOC_PATH), exist_ok=True)
    with open(DOC_PATH, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Written {DOC_PATH} ({len(Opcode)} opcodes)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
